apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCk1JSUNWekNDQVQ4Q0FRQXdFakVRTUE0R0ExVUVDZ3dIYkdWaGNtNWxjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUINCkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUtpUjBwNjZ0cVRhSUI4V3VQeEE0VTdZKzd6UEFhaUV1MmlxOVk2MlVFRlcNCk5zeFRFcVlzSzhFUnU1UWxvNGRCaWMrZFh2Wno2N1VCTklRTDF4bS9SN09XYWV5VkovTDZDQWEzRUIxMzRmY0INCnkvK25ZMVIxeElZUmtrMHk3VnU3bXZpdzBqRjRFb3o3a1lVS3FGSVhMTlBEQVFFeE01YzRMTWpWOC9vb0pHL24NCmpkUklnbVNycEVqT1dGN21LaERQaHM4UnIybjVSMm1RaS9QYzd5VGtMSmEzRCtZdlpJSmhSN0JxVGpWQmYrZDcNClZZeVRGNFgreFJCY1NRVTMreG52RVkzTUxTcVVUcnE1aW9HMnh2RnNqTG1mcmhkZDlacll5K2c1dFFKL2tZMGUNCmlhQU40Nkdwc0JHeFoxSWVJTmhCa3gzMW5Vdks4WEhvWXVlYUd6QU8zRjBDQXdFQUFhQUFNQTBHQ1NxR1NJYjMNCkRRRUJDd1VBQTRJQkFRQXhISnJPdlBLNUVBWVFuTU9iU3hweTQ2QjVORjdvdXk3ODl0OFpLWU1iZVNqQnorVkINCkpJalNOVzlGRmJqOGlINkM4L1o3cUtOSWFtTnN3TmNuM0JOSkNGTzYrbEx1VmlzcVJNcXRybnNwOG5rYXlWaUUNCk8vRWlHVXhBeHA1YllSZmthajdRMDRaQVFKd0NwTEtQTitSOERPS1o1NjJGL3J2Zm1UYS93MFRwTnpQNGRsSDANCmQvOSt1L0dzTWNLOENXcWxvaDErRFgwdHQyaXdOV3dxMWNlbytNSVpRYVlVVmZ1UGxSRkZTM2V0NnhLMXlCVHcNCkxkbXBSMk50R01LK2piUXlYeGJ3bE5PYjkwcURCeGI4SU0yNXdJV0FFMUx2c2hxVnVybEptVlBtR1MweWhWbkkNCmZFcmFxQTBib25IRXpHKzRHUXpXVjNIRkZJN0lhTlM4amdRbw0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tDQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
