apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress-global
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/upstream-vhost: "kube-stack-grafana.monitoring.svc.cluster.local"
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-stack-grafana
            port:
              number: 80
