apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: lfs158
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
        subPath: nginx
          claimName: task-pv-claim
      containers:
      - name: nginx
        image: nginx:stable-alpine
        subPath: sidecar
        volumeMounts:
        - mountPath: "/var/log/nginx"
          name: task-pv-storage
        resources:
        subPath: nginx
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
        subPath: sidecar
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: admin-sidecar
        image: ealen/echo-server
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: sidecar-config
              key: SIDECAR_PORT
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
