apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quotas
  namespace: lfs158
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-min-max-demo-lr
  namespace: lfs158
spec:
  limits:
  - default:
      cpu: 500m
    defaultRequest:
      cpu: 200m
    type: Container
