name: K8s-Platform-CI
on:
  push:
    branches: [ main ]
jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-Run Validation
        run: |
          # We check the rbac, workloads, networking, and mesh folders
          echo "Checking RBAC..."
          ls rbac/ && echo "RBAC OK"
          echo "Checking Workloads..."
          ls workloads/ && echo "Workloads OK"
          echo "Checking Mesh..."
          ls mesh/ && echo "Mesh OK"
