name: K8s-Platform-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    name: Vulnerability Scan (Trivy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan Nginx Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nginx:stable-alpine'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Scan Sidecar Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ealen/echo-server:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  validate-manifests:
    name: K8s Manifest Validation
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Kubeconform Validation
        run: |
          echo "Executing Dry-Run Validation on workloads..."
          # This ensures GitHub won't let us push broken YAML again
