name: K8s-Platform-CI
on:
  push:
    branches: [ main ]
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan Nginx
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'nginx:1.27-alpine3.20'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
